# Default values for alertmanager-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: metalmatze/alertmanager-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.4.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

secret:
  # existingSecret: ""
  adminUser: "" # not used if existingSecret is set
  botToken: "" # not used if existingSecret is set

config:
  alertmanagerUrl: http://alertmanager:9093
  logLevel: info

persistence:
  size: 1Gi
  storageClassName: local-path # default storageClass in K3s
