---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alertmanager-bot-deploy
  labels:
    app: alertmanager-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-bot
  template:
    metadata:
      labels:
        app: alertmanager-bot
    spec:
      containers:
      - name: alertmanager-bot
        image: metalmatze/alertmanager-bot:0.4.0
        envFrom:
        - secretRef:
            name: alertmanager-bot-secret
            optional: false
        - configMapRef:
            name: alertmanager-bot-configmap
            optional: false
        volumeMounts:
        - name: ambot-data
          mountPath: /data
          volumes:
      volumes: 
      - name: ambot-data
        persistentVolumeClaim:
          claimName: amdata-pvc