apiVersion: v1
kind: Service
metadata:
  name: ambot-service
  namespace: alertmanager-bot
  labels:
    app: alertmanager-bot
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alertmanager-bot