name: alertmanagerbot_ci

on:
  workflow_dispatch:
  pull_request:
    types: closed
    branches: master
  schedule:
    - cron: '0 1 * * 6'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Compile alertmanager-bot
        uses: skx/github-action-build@master
        with:
          builder: .github/build
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: hferreira/rpi-docker-openvpn:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
